default: &default
  adapter: mysql2
  # 日本向けのサービスを提供する場合はutf8mb4
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  host: <%= ENV['MYSQL_HOST'] || '127.0.0.1' %>
  port: <%= ENV['MYSQL_PORT'] || 3306 %>
  username: <%= ENV['MYSQL_USER'] || 'batch_user' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'batch' %>
  database: batch_dev

development:
  # 以下の記述で"&default"とした部分を参照する様になる
  <<: *default

test:
  <<: *default
  database: batch_test

production:
  <<: *default
  database: batch